### DISCUSSION TITLE
Setting output path fails(?) using PowerShell running on windows-latest via mcr.microsoft.com/windows/servercore:ltsc2022

### DISCUSSION THREAD

**Discussion by kohanyirobert** [ChristopherHX/runner.server#567] [Q&A] [answered]
Hey! I found your project after realizing `act` can't run workflows via Docker when working with Windows-based GitHub Actions workflows.

I managed to run your tool, but my workflow fails locally with this:

```
[Build / build] Running: Find .trx
| ##[group]Run $path = (ls -Recurse -Filter *.trx | select -First 1).FullName
| $path = (ls -Recurse -Filter *.trx | select -First 1).FullName
| "path=$path" >> $env:GITHUB_OUTPUT
| shell: pwsh -command ". '{0}'"
| env:
|   HUSKY: 0
|   NUGET_PACKAGES: C:\Users\rkohanyi\AppData\Local\runner.server\a\rn3igp3j.scv\w\DisplayDetective\DisplayDetective/.nuget/packages
|   DOTNET_ROOT: C:\Program Files\dotnet
| ##[endgroup]
| '$path' is not recognized as an internal or external command,
| operable program or batch file.
| ##[error]Process completed with exit code 255.
```

Here's my [workflow file](https://github.com/kohanyirobert/DisplayDetective/blob/feat/ci-test-reporter/.github/workflows/build.yml)., this is the interesting part:

```yml
      - name: Find .trx
        id: trx
        run: |
          $path = (ls -Recurse -Filter *.trx | select -First 1).FullName
          "path=$path" >> $env:GITHUB_OUTPUT
```

Basically I try to dynamically find a file and set an output ([as described in the official docs](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-output-parameter)).

On GitHub Actions this works, [here's one of my runs](https://github.com/kohanyirobert/DisplayDetective/actions/runs/13504079045/job/37739667242#step:8:1) (the run fails eventually, but this steps works).

Any idea? I'm unsure I'm doing something wrong or is this a bug.

This is how I run the runner: `dotnet runner.client pull_request -W .\.github\workflows\build.yml -P windows-latest=mcr.microsoft.com/windows/servercore:ltsc2022 --ref 'feat/ci-test-reporter'`

**Comment by ChristopherHX** [comment, marked as answer]
I guess the problem here is you pwsh script is run using cmd (for the same reason sh is used for linux job containers). (that the log shows pwsh instead of cmd is a bug inherited by the actions/runner, where it only applies to linux)...

My app basically rewrites your workflow a bit to have the container field set, but you are right making powershell default makes sense if you use the -P windows-latest=image syntax.

Please try the following
```yaml
      - name: Find .trx
        id: trx
        run: |
          $path = (ls -Recurse -Filter *.trx | select -First 1).FullName
          "path=$path" >> $env:GITHUB_OUTPUT
        shell: powershell # or pwsh
```
or put above your job, this makes your shell decision permanent without using defaults
```yaml
defaults:
  run:
    shell: powershell
```

Does mcr.microsoft.com/windows/servercore:ltsc2022 contain powershell or pwsh? if not you need to change your image.
