### ISSUE TITLE
azp: add `extends` template type

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#176]
based on manual testing, the following keyworlds create an error or are accepted
```yaml
# extends template
appendCommitMessageToRunName: no # fail
pr: none # fail
lockBehavior: sequential # fail
trigger: none # ok
```
