### ISSUE TITLE
azp: Add support for the undocumented alias field of container objects

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#178]
If you define an container in a string source, Azure Pipelines seems to convert it to an object

So
```yaml
container: ubuntu:latest
```
is converted to
```yaml
container:
  alias: ubuntu:latest
```
This can be important for template objects, because the container property is always using object notation in template parameters.

```yaml
resources:
  repositories:
  - repository: me
    type: git
    name: resources-in-template-files
    ref: templates
  containers:
  - container: c1
    image: ubuntu:latest
  - container: c2
    image: ubuntu:latest
parameters:
- name: jobl
  type: jobList
  default:
  - job:
    container:
      alias: ubuntu:latest
    services:
      x: 
        alias: ubuntu:latest
    steps: []
steps:
- script: ${{ converttojson(parameters.jobl) }}

```
