### ISSUE TITLE
azp: Don't crash ExpandAzurePipelines if `steps` is null

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#182]
The following template is valid in the pipeline preview api
```yaml
resources:
  repositories:
  - repository: me
    type: git
    name: resources-in-template-files
    ref: templates
  containers:
  - container: c1
    image: ubuntu:latest
  - container: c2
    image: ubuntu:latest
parameters:
- name: jobl
  type: jobList
  default:
  - job:
    container: ubuntu:latest
    services:
      x: 
        image: ubuntu:latest
   # the missing steps field is causing a null ptr error
steps:
- script: ${{ converttojson(parameters.jobl) }}

```
