### ISSUE TITLE
azp: Validate `parameters.*.values` against input and default of type `number` and `string`

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#183]
The following is ok
```yaml
- name: nb
  type: number
  default: "1.10"
  values:
    - 0
    - 1.10
    - 2.2
    - 4.5
```
This is a failure
```yaml
- name: nb
  type: number
  default: "1.10"
  values:
    - 0
    - 1.1
    - 2.2
    - 4.5
```
Only supported for string / number.

This field seem to be ignored for type boolean, therefore no error
```yaml
- name: b
  type: boolean
  default: "True"
  values:
    - "false"
```
