### ISSUE TITLE
azp: Expected a mapping error for empty each loop

### ISSUE THREAD

**Issue by bryanbcook** [ChristopherHX/runner.server#222]
The following syntax is valid in the azure-pipelines preview API

```yaml
parameters:

- name: objectArray
  type: object
  default:
  - name: one
    options:
    - a
    - b
  - name: two
    # does not specify options

stages:
- ${{ each item in parameters.objectArray }}:
  - stage: ${{ item.name }}
    jobs:
    - job: ${{ item.name }}
      steps:
      - checkout: none
      - ${{ each option in item.options }}: # errors when options is null
        - bash: echo '${{ option }}'
          displayName: 'Option ${{ option }}'
 ```

![image](https://github.com/ChristopherHX/runner.server/assets/3217452/e8e44e4f-0419-4d58-92de-50e61aef30d7)

However, when run, I get error `The template is not valid. pipeline.yml (Line: 19, Col: 9): Expected a sequence, or a mapping, got:`

I believe the issue is in the [`TemplateUnraveler:425`](https://github.com/ChristopherHX/runner.server/blob/a844212a94ba4b3bb7004df6dea17be551a28a57/src/Sdk/DTObjectTemplating/ObjectTemplating/TemplateUnraveler.cs#L422C1-L431C38), but not sure where to start.
