### ISSUE TITLE
azp: unable to resolve relative paths from within external repositories

### ISSUE THREAD

**Issue by bryanbcook** [ChristopherHX/runner.server#224]
Consider the following:

```yaml
# /pipeline.yml@self

resources:
  repositories:
  - repository: shared
    name: project/repo
    type: git
    ref: main

jobs:
- template: /templates/job.yml@shared
```
```yaml
# /templates/job.yml@shared

jobs:
- job: job1
  steps:
  - template: steps.yml # <-- relative reference within shared
```
```yaml
# /templates/steps.yml

steps:
- script: exit 0
```

Results in the `IFileProvider` attempting to resolve `project/repo@main` `/steps.yml` instead of `/templates/steps.yml`
