### ISSUE TITLE
azp: variables should not be provided when already defined in an extended pipeline

### ISSUE THREAD

**Issue by bryanbcook** [ChristopherHX/runner.server#226]
The `extend` feature does not allow you to define variables in the calling pipeline and the pipeline being extended.

The following syntax is not supported:

```yaml
# pipeline.yml

variables:
  piplineVariable: 'from pipeline'

extends:
  template: parent.yml
```

```yaml
# parent.yml

variables:
  sharedVariable: 'from extend'
  
steps:
- script: exit 0
```

Azure Pipelines provides the following error:

![image](https://github.com/ChristopherHX/runner.server/assets/3217452/dc565a92-4753-4286-ab85-51f96e438107)

To provide feature parity, an error should be provided.
