### ISSUE TITLE
azp: cannot extend pipeline with variables

### ISSUE THREAD

**Issue by bryanbcook** [ChristopherHX/runner.server#227]
Related to #226, if you define variables in the extended pipeline, it fails with a `NullReferenceException`

```yaml
# pipeline.yml
extends:
  template: base.yml
```

```yaml
# base.yml
variables:
  myVariable: variable

steps:
- script: exit 0
```

Expected: pipeline with variables from the extended template.
Actual: Object reference not set to an instance of an object.
