### ISSUE TITLE
azp: unrecognized parameters are not reported

### ISSUE THREAD

**Issue by bryanbcook** [ChristopherHX/runner.server#236]
Consider the following:

```yaml
# pipeline.yml

steps:
- template: steps.yml
  parameters:
    speltWrong: true
```

```yaml
# stages.yml
parameters:
- name: spelledWrong
  type: string
  default: ''

steps:
- script: exit 0
```

Should report an error message: `steps.yml (Line 2, Col: 1): Unexpected parameter 'speltWrong'`

But no error messages are reported.
