### ISSUE TITLE
azp: missing parameter names are not reported

### ISSUE THREAD

**Issue by bryanbcook** [ChristopherHX/runner.server#237]
Consider the following

```yaml
# pipeline.yml
steps:
- template: steps.yml
```

```yaml
# steps.yml
parameters:
- name: required
  type: string
  # no default value

steps:
- script: exit 0
```

Should report an error message `A value for the 'required' parameter must be provided'

No error message is reported
