### ISSUE TITLE
azp: missing type in array notation has type string not object

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#244]
This is invalid, but accepted by the current code
```yaml
parameters:

- name: objectArray
  type: object
  default:
  - name: one
    options:
    - a
    - b
  - name: two
    # does not specify options
- name: x
  default:
  - "Hello" # expected an error we have an array not a string
  - "x"

stages:
- ${{ each item in parameters.objectArray }}:
  - stage: ${{ item.name }}
    jobs:
    - job: ${{ item.name }}
      steps:
      - checkout: none
      - ${{ each option in item.options }}: # errors when options is null
        - bash: echo '${{ option }}'
          displayName: 'Option ${{ option }}'

```

In azure pipelines is only this valid
```yaml
parameters:

- name: objectArray
  type: object
  default:
  - name: one
    options:
    - a
    - b
  - name: two
    # does not specify options
- name: x
  default: "Hello"

stages:
- ${{ each item in parameters.objectArray }}:
  - stage: ${{ item.name }}
    jobs:
    - job: ${{ item.name }}
      steps:
      - checkout: none
      - ${{ each option in item.options }}: # errors when options is null
        - bash: echo '${{ option }}'
          displayName: 'Option ${{ option }}'
```
