### ISSUE TITLE
azp: elseif and else should fail if it isn't followed by an if

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#266]
This syntax should be rejected, due to missing if.
```yaml
steps:
  - ${{ elseif 1 }}:
    - bash: echo assert
```
