### ISSUE TITLE
azp: dynamic job variable should be available in templates for steps

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#268]
See build-job.yml of the azure pipelines agent

```yaml
parameters:
- name: test
  type: boolean
  default: true
jobs:
- job:
  variables:
    ${{ if parameters.test }}:
      requiredVar: test
  steps:
  - pwsh: ${{ variables.requiredVar }}
```
Currenty would the pwsh have an empty body

_Complex multi stage pipeline evaluation_
