### ISSUE TITLE
Runner.Worker Killed when running on macos M2

### ISSUE THREAD

**Issue by oilrich25** [ChristopherHX/runner.server#284]
Runner.Worker crashes when running on macos M2. The version I am currently testing is v3.11.11.
```
oilrich25deMac-mini:Desktop oilrich25$ ./actions-runner/bin/Runner.Worker 
System.ArgumentOutOfRangeException: Length does not equal expected value. Expected '3'. Actual '0'. (Parameter 'Length')
Actual value was 0.
   at GitHub.Runner.Sdk.ArgUtil.Equal[T](T expected, T actual, String name)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
oilrich25deMac-mini:Desktop oilrich25$ ./runner.server-osx-arm64/bin/Runner.Worker 
Killed: 9
oilrich25deMac-mini:Desktop oilrich25$ file ./actions-runner/bin/Runner.Worker 
./actions-runner/bin/Runner.Worker: Mach-O 64-bit executable arm64
oilrich25deMac-mini:Desktop oilrich25$ file ./runner.server-osx-arm64/bin/Runner.Worker 
./runner.server-osx-arm64/bin/Runner.Worker: Mach-O 64-bit executable arm64


(lldb) target create "./runner.server-osx-arm64/bin/Runner.Worker"
Current executable set to '/Users/oilrich25/Desktop/gitea-actions-runner/runner.server-osx-arm64/bin/Runner.Worker' (arm64).
(lldb) run
error: process exited with status -1 (no such process.)
(lldb) breakpoint set --name main
Breakpoint 1: where = Runner.Worker`main, address = 0x000000010000d570
(lldb) run
error: process exited with status -1 (no such process.)
```

**Comment by oilrich25** [comment]
> You cannot start `Runner.Worker` without specfic args. My actions-runner-worker.ps1 or .py scripts are adding args and setup pipe communications.
> 
> To register and run against `Runner.Server` you would use `Runner.Listener configure` and `Runner.Listener run`

I tried downgrading v3.11.11 to v3.9 and it works fine now

**Comment by oilrich25** [comment]
After testing, on mac M2, execute arm64 ubuntu
Docker containers are feasible. But unfortunately it can only run on 3.9.2 currently.
```
##[group]Run uname -a
uname -a
shell: bash --noprofile --norc -e -o pipefail {0}
env:
  CACHE_EPOCH: 1
  CCACHE_MAXFILES: 0
  CCACHE_MAXSIZE: 200M
  SCCACHE_CACHE_SIZE: 200M
##[endgroup]
Linux f54dd1cdb107 6.5.11-linuxkit #1 SMP PREEMPT Mon Dec  4 11:30:00 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

v3.11.11, the `Killed: 9` error occurred.
