### ISSUE TITLE
Proposal to Disable GitHub Authentication Requirement for ghcr.io Prefix

### ISSUE THREAD

**Issue by oilrich25** [ChristopherHX/runner.server#286]
### Issue Description
When using `ChristopherHX/gitea-actions-runner` with `actions/runner` or `ChristopherHX/runner.server`, I noticed that GitHub authentication is triggered when the container has the `ghcr.io` prefix. However, in practical use, especially when running workflows in Gitea, this login is not necessary.

### Suggestion
I suggest disabling the functionality that requires GitHub authentication whenever the container has the `ghcr.io` prefix.

### Reference Code
The relevant code snippet can be found in [ContainerOperationProvider.cs](https://github.com/ChristopherHX/runner.server/blob/main/src/Runner.Worker/ContainerOperationProvider.cs#L219):
```
jobs:
  windows:
    runs-on: windows-2019
    container: 
      image: ghcr.io/faithlife/actions-runner-image:ltsc2019
      credentials:
        username: oilrich25
        password: xxxxxxxxxxxxx
```

Expected ### Result
I expect that there won't be a need for GitHub authentication when using containers with the `ghcr.io` prefix, especially when running workflows in Gitea.
