### ISSUE TITLE
azp: Use the format functions for Expressions v1 in Azure Pipelines for single expressions

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#291]
```yaml
steps:
- script: ${{ format(not(False)) }}
- script: ${{ not(False) }}
```

currently outputs

```yaml
stages:
- stage: 
  jobs:
  - job: 
    steps:
    - task: CmdLine@2
      inputs:
        script: True
    - task: CmdLine@2
      inputs:
        script: true
```

instead of

```yaml
stages:
- stage: 
  jobs:
  - job: 
    steps:
    - task: CmdLine@2
      inputs:
        script: True
    - task: CmdLine@2
      inputs:
        script: True
```
