### ISSUE TITLE
azp: Null pointer exception

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#299]
```yaml
parameters:
- name: variables
  type: object
  default:
  - name: x
    value: e
variables: ${{ parameters.variables }}
steps:
- script: ${{ format(not(False)) }}
- script: ${{ not(true) }}
```

Caused by assigning variables to an expression / null
