### ISSUE TITLE
azp: make varables in template references available at template expansion

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#317]
`buildConfig` in `vars.yml` should get expanded with the value from the template
```yaml
variables:
  - template: ./vars.yml
  - name: ncfg
    value: TEST-${{ variables.buildConfig }}
steps:
- bash: ${{ variables.ncfg }}
```

Problem Found in dotnet/runtime/eng/pipelines/runtime.yml
