### ISSUE TITLE
azp: Too weak job continueOnError validation

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#333]
`/azure-pipeline.yml (Line: 7, Col: 22): Expected a Boolean value. Actual value: '$'`

```yaml
parameters: []
stages:
- stage:
  jobs:
  - job:
    dependsOn: ""
    continueOnError: $
    steps:
    - script: echo 0
```

While `$[ ... ]`  are more strict
