### ISSUE TITLE
azp: Too weak job condition validation

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#334]
Azure pipelines either never accepted `$[ ... ]` inside a job condition or stopped supporting it

```yaml
parameters: []
stages:
- stage:
  jobs:
  - job:
    dependsOn: ""
    condition: $[ succeeded() ]
    steps:
    - script: echo 0
```
