### ISSUE TITLE
azp: continueOnError: n is broken

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#335]
```yaml
parameters:
  - name: jobs
    type: jobList
    default:
    - job: positive_test
      #condition: $[fff]
      templateContext:
        expectedHTTPResponseCode: 200
        requiredComponents: dimensionsapi
      steps:
      - script: ./runPositiveTest.sh
        continueOnError: n
    - job: negative_test
      templateContext:
        expectedHTTPResponseCode: 500
        requiredComponents: dimensionsapi
      steps:
      - script: ./runNegativeTest.sh
jobs:
- ${{ parameters.jobs }}
- job:
  steps:
  - bash: ${{converttojson(parameters.jobs) }}
```
