### ISSUE TITLE
Switch to Unicode Console Encoding

### ISSUE THREAD

**Issue by JustinGrote** [ChristopherHX/runner.server#35]
Currently unicode characters in Github Actions do not appear correctly (substituted with ??) and the output encoding should be changed to unicode.

![image](https://user-images.githubusercontent.com/15258962/118004626-79cf5400-b2fe-11eb-8aa9-9de36ae14b0d.png)

**Comment by ChristopherHX** [comment]
Are you using "Windows Terminal"? Conhost doesn't replace the invalid encoding with ??.

I wonder why powershells echo still kills the encoding, this seems to happen on the Runner.Worker. 
```
on: push
jobs:
    test:
        name: samplejob 🎐
        runs-on: self-hosted
        steps:
        - run: echo Hello World 🎐
```

Looks for me
![image](https://user-images.githubusercontent.com/44845461/118029053-0d873b80-b364-11eb-9942-befa513f6534.png)

You can type `chcp 65001` then run it without a patch works too
