### ISSUE TITLE
azp: Extension 0.0.22 Full Pipeline Schema

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#371]
some known issues
```yaml
trigger: none
variables:
  - template: /eng/pipelines/common/variables.yml
extends:
  template:  /eng/pipelines/common/templates/pipeline-with-resources.yml
  parameters:
    stages:
    - stage: Build
      jobs:
      - template: /eng/pipelines/extra-platforms/runtime-extra-platforms-androidemulator.yml
        parameters:
          isExtraPlatformsBuild: ${{ variables.isExtraPlatformsBuild }}
          isAndroidEmulatorOnlyBuild: ${{ variables.isAndroidEmulatorOnlyBuild }}
          isRollingBuild: ${{ variables.isRollingBuild }}

```

also the subtemplates are probably affected, requires more overrides
