### ISSUE TITLE
azp: add support for stage level trigger for template expansion

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#388]
Example from <https://learn.microsoft.com/en-us/azure/devops/release-notes/2024/pipelines/sprint-243-update#manually-triggered-yaml-pipeline-stages>
```yaml
stages:
- stage: stage_WUS1
  displayName: Deploy WUS1
  trigger: manual
  jobs:
  - job: DeployJob
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureWIF'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: 'Write-host ''hello, world'''     
- stage: stage_WUS2
  displayName: Deploy WUS2
  trigger: manual
  jobs:
  - job: DeployJob
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureWIF'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: 'Write-host ''hello, world'''
```

Syntax only validation supports this already, seems like the schema from dev azure did contain information of upcoming changelog entries
