### ISSUE TITLE
Troubleshooting Remote Template References

### ISSUE THREAD

**Issue by iTiamo** [ChristopherHX/runner.server#435]
Hello Christopher,

Thanks for the amazing extension. I use it with much pleasure. In my current organization we use a lot of remote templates, meaning that it would be really useful to have remote template references, but I can not seem to set it up correctly.

I am trying to extend a remote template and use the Azure Pipelines Tools extension to validate my pipeline. My pipeline looks a little bit like this:

```yaml
...

resources:
  repositories:
    - repository: shared-templates
      name: myorg/azure-devops-templates
      type: git
      ref: refs/tags/20241104.1

extends:
  template: pipelines/master-pipeline.yml@shared-templates
  parameters:
    buildJobs: ...
    deployJobs: ...

...
```

Whenever I run Validate Azure Pipeline from the Command Palette, I get prompted to provide an URI for the remote repository:

![image](https://github.com/user-attachments/assets/0daa01e9-c8fd-4f05-83fd-9e035537278a)

I really like this flow. Here I enter the repository URI that I would find when I would clone the repository in the Azure DevOps UI:

![image](https://github.com/user-attachments/assets/3e986011-9e14-47c5-aa34-bc9b8d49cd98)

However, this leads to an error as stated below:

```
[error]Couldn't read template pipelines/master-pipeline.yml@azure-devops-templates resolved to pipelines/master-pipeline.yml (myorg/azure-devops-templates@refs/tags/20241104.1)
```

Since the message seems to suggest that it tries to resolve the pipeline template to `pipelines/master-pipeline.yml` I tried to place the repository files here manually for debugging purposes but the message remains.

Could you provide some guidance as to what I am doing wrong?

Many thanks!
