### ISSUE TITLE
Somehow we get a parse error here

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#446]
```yaml
parameters:
- name: group
  type: object
  default:
  - 'myGroup'
- name: resources
  type: object
  default:
  - resourceNames:
    - 'name1'
    - 'name2'

jobs:
- job: TestJob

  steps:  
  - ${{ each r in parameters.resources }}:
        
      
   
        - ${{ each n in coalesce(replace(r.resourceNames, True, False), parameters.group) }}:
        
        
             - script: echo ${{ n }}
```

Only runtime error expected
