### ISSUE TITLE
Suggest all required properties when suggesting creating a mapping

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#467]
e.g.

in an action.yml
```yaml
runs:
  using:
    steps:
    - 
```
When taking the shell key also insert run and vice versa.
