### ISSUE TITLE
Stage variables in expressions within each are not expanded

### ISSUE THREAD

**Issue by zdenek-jelinek** [ChristopherHX/runner.server#514]
It appears that when variables are used within a stage within each expression, accessing the variables through expression does not work.

Given the following example pipeline that generates two stages that output "Hello, World{!.}":
```yml
trigger:
  none

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

parameters:
- name: Suffixes
  displayName: Message suffixes
  type: object
  default:
  - Name: Exclamation
    Value: '!'
  - Name: FullStop
    Value: '.'

stages:
- ${{ each suffix in parameters.Suffixes }}:
  - stage: print_with_${{ suffix.Name }}
    displayName: Print message with '${{ suffix.Name }}'

    variables:
      Message: Hello, World${{ suffix.Value }}

    jobs:
    - job: print_with_${{ suffix.Name }}
      steps:
      - checkout: none
      - script: echo "${{ variables.Message }}"
```

expansion using the tool produces

```yml
trigger: none
stages:
- stage: print_with_Exclamation
  displayName: Print message with 'Exclamation'
  variables:
  - name: Message
    value: Hello, World!
  jobs:
  - job: print_with_Exclamation
    steps:
    - task: Checkout@1
      inputs:
        repository: none
    - task: CmdLine@2
      inputs:
        script: echo ""
- stage: print_with_FullStop
  displayName: Print message with 'FullStop'
  variables:
  - name: Message
    value: Hello, World.
  jobs:
  - job: print_with_FullStop
    steps:
    - task: Checkout@1
      inputs:
        repository: none
    - task: CmdLine@2
      inputs:
        script: echo ""
pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
```

_Note the `script: echo ""` present in both stages_

When run on an Azure DevOps agent, both of the scripts output the actual `Message` variable, i.e. `Hello, World!` and `Hello, World.` according to the respective stage.

The expanded yaml from the run is:

```yml
trigger:
  enabled: false
pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest
stages:
- stage: print_with_Exclamation
  displayName: Print message with 'Exclamation'
  variables:
  - name: Message
    value: Hello, World!
  jobs:
  - job: print_with_Exclamation
    steps:
    - task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
      condition: false
      inputs:
        repository: none
    - task: CmdLine@2
      inputs:
        script: echo "Hello, World!"
- stage: print_with_FullStop
  displayName: Print message with 'FullStop'
  variables:
  - name: Message
    value: Hello, World.
  jobs:
  - job: print_with_FullStop
    steps:
    - task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
      condition: false
      inputs:
        repository: none
    - task: CmdLine@2
      inputs:
        script: echo "Hello, World."
```

I came across this when generating stages based on template parameters in similar fashion to what is done here.
