### ISSUE TITLE
azp: accessing variable names with minus should cause an error without quotes

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#515]
This workflow should be invalid

```yaml
variables:
- name: test-b
  value: xy
- name: vars
  value: ${{converttojson(variables)}}
- ${{ if variables.test-b }}:
  - name: vars2
    value: ${{converttojson(variables)}}
steps:
- bash: test
```
