### ISSUE TITLE
azp: parameter prompt default value in extension is quoted

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#607]
```yaml
parameters:
  - name: VSCODE_QUALITY
    displayName: Quality
    type: string
    default: insider
    values:
      - exploration
      - insider
      - stable
```

I expect to only see insider
