### ISSUE TITLE
azp: templates without ./ or ../ are absolute not relative

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#608]
build/azure-pipelines/test.yml
```yaml
extends:
     template: /some/path/test.yml
     parameters:
       steps:
         - template: build/azure-pipelines/linux/cli-build-linux.yml@self
```
