### ISSUE TITLE
Unable to clone repository with act

### ISSUE THREAD

**Issue by Startouf** [ChristopherHX/runner.server#611]
Hello, when trying to run Act, I run into the following error

```
[Build and push docker image on AWS/build]   ☁  git clone 'https://github.com/aws-actions/configure-aws-credentials' # ref=v1
[Build and push docker image on AWS/build] Unable to clone https://github.com/aws-actions/configure-aws-credentials refs/heads/v1: authentication required: Invalid username or password.
```

The repository in question is publicly available here : https://github.com/aws-actions/configure-aws-credentials

Full log

```
act push --container-architecture linux/amd64
INFO[0000] Using docker host 'unix:///var/run/docker.sock', and daemon socket 'unix:///var/run/docker.sock' 
[Build and push docker image on AWS/build] ⭐ Run Set up job
[Build and push docker image on AWS/build] 🚀  Start image=catthehacker/ubuntu:act-latest
[Build and push docker image on AWS/build]   🐳  docker pull image=catthehacker/ubuntu:act-latest platform=linux/amd64 username= forcePull=true
[Build and push docker image on AWS/build] using DockerAuthConfig authentication for docker pull
[Build and push docker image on AWS/build]   🐳  docker create image=catthehacker/ubuntu:act-latest platform=linux/amd64 entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[Build and push docker image on AWS/build]   🐳  docker run image=catthehacker/ubuntu:act-latest platform=linux/amd64 entrypoint=["tail" "-f" "/dev/null"] cmd=[] network="host"
[Build and push docker image on AWS/build]   🐳  docker exec cmd=[node --no-warnings -e console.log(process.execPath)] user= workdir=
[Build and push docker image on AWS/build]   ✅  Success - Set up job
[Build and push docker image on AWS/build]   ☁  git clone 'https://github.com/aws-actions/configure-aws-credentials' # ref=v1
[Build and push docker image on AWS/build] Unable to clone https://github.com/aws-actions/configure-aws-credentials refs/heads/v1: authentication required: Invalid username or password.
[Build and push docker image on AWS/build] authentication required: Invalid username or password.
[Build and push docker image on AWS/build] ⭐ Run Complete job
[Build and push docker image on AWS/build]   ✅  Success - Complete job
[Build and push docker image on AWS/build] 🏁  Job failed
Error: authentication required: Invalid username or password.
```

My workflow

```
name: Build and push docker image on AWS
on:
  push:
  workflow_dispatch:
    inputs:
      ref:
        description: 'GitHub REF to be used for checkout'
        required: false
      sha:
        description: 'GitHub SHA to be used for checkout'
        required: true
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      XXX
    steps:
      - name: Set Friendly tag
        run: echo "FRIENDLY_TAG=$(echo ${GITHUB_REF} | cut -c12-)#$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker images & push to AWS
        run: ./scripts/build_and_push_docker_image_to_aws.sh
        env:
          DOCKER_BUILDKIT: 1
```

Any idea what could go wrong ? `git clone 'https://github.com/aws-actions/configure-aws-credentials' # ref=v1` this command is working locally
