### ISSUE TITLE
environment tags not expanded on a deployment job

### ISSUE THREAD

**Issue by bjuraga** [ChristopherHX/runner.server#612]
Using the addon in Visual Studio Code, v0.2.13 and the following YAML:
``` yaml
jobs:
  - deployment: Production
    displayName: Production
    environment:
      name: Production
      resourceType: VirtualMachine
      tags: ABC
```

Every line of the above YAML is present in the expanded pipeline, **except for the tags**.
