### ISSUE TITLE
Not able to find node12

### ISSUE THREAD

**Issue by bhvngt** [ChristopherHX/runner.server#72]
**Describe the bug**
While Running `Runner.client`, following error is thrown

`OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/__e/linux/amd64/node12/bin/node": stat /__e/linux/amd64/node12/bin/node: no such file or directory: unknown`

**To Reproduce**
1. Go to <repo root>
2. Run 'Runner.client'
3. See error

**Expected behavior**
To complete the run successfully

## Runner Version and Platform
Version of your runner? `3.2.1`

OS of the machine running the runner? OSX/Windows/Linux/... `OSX`

## What's not working?
```
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "/__e/linux/amd64/node12/bin/node": stat /__e/linux/amd64/node12/bin/node: no such file or directory: unknown
```

## Job Log Output
[log output](https://gist.github.com/bhvngt/a4de1f5df81b645a6009b1b9601ff7f2)

## Runner and Worker's Diagnostic Logs
github action
```
name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
```

**Comment by ChristopherHX** [comment]
I'm unable to reproduce this problem (macOS 10.14), I need your help to identify the problem on your system.
- post the output of `ls -l /usr/local/opt/github-actions-runner/actions-runner/externals/linux/amd64/node12/bin` to see permissions on macOS
- Post the output of the following workflow to see permissions on Linux (Docker)
```
name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: ls -l /__e/linux/amd64/node12/bin
```
- Run `sudo rm -rf /usr/local/opt/github-actions-runner/actions-runner/externals/`, to let the runner downloading a fresh copy of node (even if any previous point fails to run)
- Run `Runner.Client` again and post the output.

I hope to find a way to autofix this error inside the Runner.

**Comment by bhvngt** [comment]
Thanks @ChristopherHX.

Here you go

output of `ls -l /usr/local/opt/github-actions-runner/actions-runner/externals/linux/amd64/node12/bin` on OSX
```
total 44540
-rwxr-xr-x 1 Bhavin admin 45605784 Nov 19  2019 node
lrwxr-xr-x 1 Bhavin admin       38 Nov 19  2019 npm -> ../lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x 1 Bhavin admin       38 Nov 19  2019 npx -> ../lib/node_modules/npm/bin/npx-cli.js
```

Ran
`sudo rm -rf /usr/local/opt/github-actions-runner/actions-runner/externals/`

Ran `Runner.Client` with following `job`
```
name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - run: ls -l /__e/linux/amd64/node12/bin
```
Here's the output
[Job Log Output](https://gist.github.com/bhvngt/ceaeee23362c584f5020090f9eaaa0c3)
