### ISSUE TITLE
Skipping jobs with a name using expression syntax leads to job failure.

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#74]
**Describe the bug**
Skipping jobs with a name using expression syntax leads to job failure.

**To Reproduce**
Run this workflow
```yaml
on: push
jobs:
  test:
    name: ${{github.event_name}}
    runs-on: ubuntu-latest
    if: 'false'
    steps:
    - run: exit 0
```

**Expected behavior**
Job get status skipped instead of failure and workflow does succeed.

## Runner Version and Platform
Version of your runner? 3.3.3

OS of the machine running the runner? Any
