### ISSUE TITLE
[WEBUI] leading spaces in log are truncated

### ISSUE THREAD

**Issue by ChristopherHX** [ChristopherHX/runner.server#75]
**Describe the bug**
If the job logoutput conatains leading spaces, you won't see them in the webconsole.

**To Reproduce**
Run this workflow
```yaml
on: push
jobs:
  test:
    name: ${{github.event_name}}
    runs-on: ubuntu-latest
    if: 'false'
    steps:
    - run: echo "    Hello leading space"
```
and look at the webconsole log.

**Expected behavior**
leading spaces are displayed and not truncated.

## Runner Version and Platform
Version of your runner? 3.3.3

OS of the machine running the runner? Any

## Possible solution:
replace css `white-space: nowrap` with `white-space: pre` to display leading spaces
